server:
  port: 8084

spring:
  application:
    name: RATING-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/rating_db
    username: postgres
    password: Ramish@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
